### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by savmus** [savmus/humble#1]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by savmus** [comment]
Pushed to Heroku and ready for review

**Comment by wongshington** [comment]
- [ ] the errors shouldn't carry over when switching forms from login to signup etc.
- [ ] bigger text boxes with bigger font all around
- [ ]  add the demo login button to the signup form as well

**Comment by savmus** [comment]
Pushed changes to Heroku

**Comment by wongshington** [comment]
- [ ] the errors either aren't correct or don't clear properly. 
    - if i try to sign up without a username the first time I get the right error, but if i then add the username the next time, it will say the other fields can't be blank etc.

**Comment by savmus** [comment]
Pushed to Heroku
