### ISSUE TITLE
PA Review: Posts

### ISSUE THREAD

**Issue by savmus** [savmus/humble#2]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by savmus** [comment]
Pushed to Heroku for review

**Comment by wongshington** [comment]
- [ ] it looks like clicking buttons around your site causes a refresh of the entire page
- [ ] I shouldn't be able to post an empty post
- [ ] this feels like it should work: 
![Screen Shot 2019-08-07 at 2 42 24 PM](https://user-images.githubusercontent.com/26219652/62660036-d4fe3680-b921-11e9-81f4-8ebe94ab5544.png)
- [ ] form should be on the same page as the feed
